### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Scratchy144** [mrcool4000/splix-auto-downloader#1]
Splix auto downloader is useless when it comes to functionality. It can be EASILY replaced with a process.open as it is much easier. Please note that the class won't work UNLESS if you completely rewrite the ENTIRE code to "format" it for Splix. Please make this WORK.
Thanks, Scratchy

**Comment by mrcool4000** [comment]
Dude!
I taught you how to use this app.
And it works fine.

**Comment by raghav-misra** [comment]
@Scratchy144  : Hi Scratchy, thanks a million for taking the time to post an issue. What do you mean by *rewrite the ENTIRE code* and Process.Open(----) is not a substitute for this code.

**Comment by raghav-misra** [comment]
@Scratchy144 holy ragebait

**Comment by LehuyH** [comment]
@raghav-misra zawg doesn't compile no more

**Comment by LehuyH** [comment]
How to rollback update in case of supply chain attack @raghav-misra

**Comment by LehuyH** [comment]
Also how to do channel releases for EU brothers who need different binary
